apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-friends-tls
spec:
  secretName: k8s-friend
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: exposeyourfriends.ru
  dnsNames:
    - exposeyourfriends.ru
    - www.exposeyourfriends.ru
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - exposeyourfriends.ru
          - www.exposeyourfriends.ru

